# monitoring/docker-compose.yml
version: '3'

services:
  # Loki: Sammelt die Logs
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # Prometheus: Sammelt die Metriken
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana: Visualisiert alles
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # Wir mappen auf Port 3001, da 3000 schon von unserem Backend belegt ist
    depends_on:
      - loki
      - prometheus